### ISSUE TITLE
Departure Label background_color goes over nosid_color

### ISSUE THREAD

**Issue by erikwachters** [pierr3/vSMR#57]
Hi,

I've tested the nightly build and all works fine. 
The only thing is that if an A/C has no SID still has the "background_color" color and not the "nosid_color". Maybe the "nofpl_color" has the same problem?

Another idea for implementation is that you can choose that the font size of the first line is bigger than the 2nd & 3th & ..... line so that the C/S is bigger than the info in the other lines.

Regards,

E.

**Comment by keanucz** [comment]
It will only use "background_color" if it can't find "nosid_color"/"nofpl_color". As for the font size, I will look into it.

**Comment by erikwachters** [comment]
Hi,
I tested it in a sweatbox session and I have the "background_color" on an aircarft without SID instead of the "nosid_color".
Screenshot: http://prntscr.com/qgrb3g

My config:
        "departure": {
            "definition": [
                ["callsign", "wake"],
                ["seprwy", "sqerror"]
            ],
            "nofpl_color": {
                "r": 0,
                "g": 100,
                "b": 170,
                "a": 255
            },
            "nosid_color": {
                "r": 230,
                "g": 0,
                "b": 230,
                "a": 255
            },
            "background_color": {
                "r": 0,
                "g": 200,
                "b": 190,
                "a": 255
            },
            "background_color_on_runway": {
                "r": 40,
                "g": 255,
                "b": 240,
                "a": 255
            },
            "text_color": {
                "r": 0,
                "g": 0,
                "b": 0
            }
        },

Normally the label must be pink.

E.

**Comment by keanucz** [comment]
Hrm hrm hrm.. so this isn't just a quirk. I'll look into it.

**Comment by pierr3** [comment]
@Keanu73 anything you were able to find related to this?

**Comment by keanucz** [comment]
Not yet, so far..

**Comment by pierr3** [comment]
@erikwachters on your screenshot, was that aircraft VFR? VFRs are excluded from the Nosid/sid colour logic, let me know if you think that should change.

Re/text bigger on L1, I'd like to implement but in the current architecture it's going to be a bit complex

**Comment by hpeter2** [comment]
Explanation:
Method _CSMRRadar::OnRefresh_, region tags does the following check:
`if (fp.GetFlightPlanData().GetPlanType() == "I" && TagReplacingMap["asid"].empty() && LabelsSettings[Utils::getEnumString(ColorTagType).c_str()].HasMember("nosid_color")) {...}`

The first part of that mentioned check unfortunately never succeeds, even if the Flightplan-Type is IFR ('I'). (See attached screenshot)
This can be fixed by changing this check to a character comparison:
`fp.GetFlightPlanData().GetPlanType()[0] == 'I'`

The same has to be applied to method _CInsetWindow::render_ of the Inset-Window.

![bug_57](https://user-images.githubusercontent.com/35301138/92234801-fa59cd00-eeb2-11ea-96b2-2d03516ea357.PNG)

---

"nofpl_color" will never be used, as the check is only applied on Departure tag types. Aircraft without a flightplan can't be defined as departing ones. The check
`if (TagReplacingMap["actype"] == "NoFPL" && LabelsSettings[Utils::getEnumString(ColorTagType).c_str()].HasMember("nofpl_color")) {...}`
should be outside and below the _ColorTagType == TagTypes::Departure_ bracket (again, Radar & Inset)

**Comment by hpeter2** [comment]
I forgot, the _"nofpl_color"_ configuration has to be below Tag-Type "uncorrelated"

**Comment by pierr3** [comment]
Thanks @hpeter2 ! I am having a look, so far your code looks great! Could you open pull request for this if you so wish?

**Comment by pierr3** [comment]
Should be fixed in nightly thanks to @hpeter2 !
