### ISSUE TITLE
Be able to use telext in euroscope and hoppie's ACARS

### ISSUE THREAD

**Issue by GreenJetsam** [pierr3/vSMR#70]
We can send and receive PDC requests with a custom message at the end but can't receive or send telext, any chance in the CPDLC chat menu there could be a command to send freetext to an aircraft and see received messages.

**Comment by pierr3** [comment]
This is not really in scope of this project, so unlikely to implement, but thanks for the suggestion.

**Comment by GreenJetsam** [comment]
Apologies for asking but how isnt telex (part of the real world CPDLC system) in the scope of this as many pilots and controllers use it for operational info like changing of clearances etc. Just out of interest how it isn’t something that could be implemented in the same way pdc is implemented? Possibly with a simple .smr [callsign] [message]

**Comment by kusterjs** [comment]
Because the PDC/DCL is only using a part of CPDLC functionalities, if any (depending on the actual used system implementation). But common for all is that a single freetext can be provided with the clearance. However, further exchanges of freetext are not possible.
You should use the hoppie client for using any CPDLC functionalities. However, be advised that telext messages are not using for PDC/DCL part. As vSMR is a simulation of an A-SMGCS, any such functionality isn't really the core business.

**Comment by GreenJetsam** [comment]
Ah right thank you for clearing that up. Love what you’re doing here and thank you :)
